package Lab6P2_LloydCooperr;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class frameMain extends javax.swing.JFrame {
    
    private ArrayList <Consola> consolas = new ArrayList();
    private ArrayList <Juego> juegos = new ArrayList();
    public frameMain() {
        initComponents();
        this.setLocationRelativeTo(null);
        dialogModificarConsola.setVisible(false);
        dialogVerJuegos.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        popUpMenu = new javax.swing.JPopupMenu();
        modificarConsola = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        eliminarConsola = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        listarJuegos = new javax.swing.JMenuItem();
        dialogModificarConsola = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        tfIdentificacionConsola1 = new javax.swing.JTextField();
        tfFabricanteConsola1 = new javax.swing.JTextField();
        tfAñosUsoConsola1 = new javax.swing.JTextField();
        tfPrecioConsola1 = new javax.swing.JTextField();
        tfModeloConsola1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnModificarConsola = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        tfNumeroControles1 = new javax.swing.JTextField();
        tfAlmacenamientoConsola1 = new javax.swing.JTextField();
        tfTipoConexion1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        dialogVerJuegos = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        tfIdentificacionConsola = new javax.swing.JTextField();
        tfFabricanteConsola = new javax.swing.JTextField();
        tfAñosUsoConsola = new javax.swing.JTextField();
        tfPrecioConsola = new javax.swing.JTextField();
        tfModeloConsola = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCrearConsola = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tfNumeroControles = new javax.swing.JTextField();
        tfAlmacenamientoConsola = new javax.swing.JTextField();
        tfTipoConexion = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        tfIdentificacionPortatil = new javax.swing.JTextField();
        tfFabricantePortatil = new javax.swing.JTextField();
        tfAñosUsoPortatil = new javax.swing.JTextField();
        tfPrecioPortatil = new javax.swing.JTextField();
        tfModeloPortatil = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnCrearPortatil1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        tfTamañoPantalla = new javax.swing.JTextField();
        tfBateriaPortatil = new javax.swing.JTextField();
        rbNo = new javax.swing.JRadioButton();
        rbSi = new javax.swing.JRadioButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableConsolas = new javax.swing.JTable();

        modificarConsola.setText("Modificar consola");
        modificarConsola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarConsolaActionPerformed(evt);
            }
        });
        popUpMenu.add(modificarConsola);
        popUpMenu.add(jSeparator1);

        eliminarConsola.setText("Eliminar consola");
        eliminarConsola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarConsolaActionPerformed(evt);
            }
        });
        popUpMenu.add(eliminarConsola);
        popUpMenu.add(jSeparator2);

        listarJuegos.setText("Ver juegos");
        listarJuegos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarJuegosActionPerformed(evt);
            }
        });
        popUpMenu.add(listarJuegos);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Identificacion de la consola");

        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Fabricante de la consola");

        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Años de uso de la consola");

        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Precio de la consola");

        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Modelo de la consola");

        btnModificarConsola.setText("Modificar consola");
        btnModificarConsola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarConsolaMouseClicked(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Modificar consola");

        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Numero de controles");

        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Almacenamiento");

        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Tipo de conexion");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnModificarConsola)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfTipoConexion1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(tfAlmacenamientoConsola1)
                                    .addComponent(tfNumeroControles1)
                                    .addComponent(tfIdentificacionConsola1)
                                    .addComponent(tfFabricanteConsola1)
                                    .addComponent(tfAñosUsoConsola1)
                                    .addComponent(tfPrecioConsola1)
                                    .addComponent(tfModeloConsola1))))
                        .addGap(225, 225, 225))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfIdentificacionConsola1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfFabricanteConsola1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAñosUsoConsola1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPrecioConsola1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfModeloConsola1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNumeroControles1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAlmacenamientoConsola1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTipoConexion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnModificarConsola)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout dialogModificarConsolaLayout = new javax.swing.GroupLayout(dialogModificarConsola.getContentPane());
        dialogModificarConsola.getContentPane().setLayout(dialogModificarConsolaLayout);
        dialogModificarConsolaLayout.setHorizontalGroup(
            dialogModificarConsolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(dialogModificarConsolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dialogModificarConsolaLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        dialogModificarConsolaLayout.setVerticalGroup(
            dialogModificarConsolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 391, Short.MAX_VALUE)
            .addGroup(dialogModificarConsolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dialogModificarConsolaLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout dialogVerJuegosLayout = new javax.swing.GroupLayout(dialogVerJuegos.getContentPane());
        dialogVerJuegos.getContentPane().setLayout(dialogVerJuegosLayout);
        dialogVerJuegosLayout.setHorizontalGroup(
            dialogVerJuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dialogVerJuegosLayout.setVerticalGroup(
            dialogVerJuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Identificacion de la consola");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Fabricante de la consola");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Años de uso de la consola");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Precio de la consola");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Modelo de la consola");

        btnCrearConsola.setText("Agregar consola");
        btnCrearConsola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearConsolaMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Crear consola");

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Numero de controles");

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Almacenamiento");

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Tipo de conexion");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCrearConsola)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfTipoConexion, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(tfAlmacenamientoConsola)
                                    .addComponent(tfNumeroControles)
                                    .addComponent(tfIdentificacionConsola)
                                    .addComponent(tfFabricanteConsola)
                                    .addComponent(tfAñosUsoConsola)
                                    .addComponent(tfPrecioConsola)
                                    .addComponent(tfModeloConsola))))
                        .addGap(225, 225, 225))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfIdentificacionConsola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfFabricanteConsola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAñosUsoConsola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPrecioConsola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfModeloConsola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNumeroControles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAlmacenamientoConsola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTipoConexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCrearConsola)
                .addGap(34, 34, 34))
        );

        jTabbedPane1.addTab("Crear consola", jPanel1);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Identificacion de la consola");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Fabricante de la consola");

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Años de uso de la consola");

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Precio de la consola");

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Modelo de la consola");

        btnCrearPortatil1.setText("Agregar portatil");
        btnCrearPortatil1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearPortatil1MouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Crear portatil");

        buttonGroup1.add(rbNo);
        rbNo.setText("No");

        buttonGroup1.add(rbSi);
        rbSi.setText("Si");

        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Tamaño de la pantalla");

        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Duracion de bateria");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btnCrearPortatil1)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel12)
                        .addGap(224, 224, 224))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfBateriaPortatil)
                    .addComponent(tfTamañoPantalla)
                    .addComponent(tfIdentificacionPortatil)
                    .addComponent(tfFabricantePortatil)
                    .addComponent(tfAñosUsoPortatil)
                    .addComponent(tfPrecioPortatil)
                    .addComponent(tfModeloPortatil, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbSi)
                    .addComponent(rbNo))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfIdentificacionPortatil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(rbSi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfFabricantePortatil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(rbNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAñosUsoPortatil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPrecioPortatil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfModeloPortatil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTamañoPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfBateriaPortatil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btnCrearPortatil1)
                .addGap(34, 34, 34))
        );

        jTabbedPane1.addTab("Crear portatil", jPanel4);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        tableConsolas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificacion", "Fabricante", "Modelo", "Años de uso", "Precio", "Tipo de consola"
            }
        ));
        tableConsolas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableConsolasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableConsolas);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listar consola", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearConsolaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearConsolaMouseClicked
        String identificacion = tfIdentificacionConsola.getText().toUpperCase();
        String fabricante = tfFabricanteConsola.getText();
        int añosUso = Integer.parseInt(tfAñosUsoConsola.getText());
        int precio = Integer.parseInt(tfPrecioConsola.getText());
        String modelo = tfModeloConsola.getText();
        int numeroControles = Integer.parseInt(tfNumeroControles.getText());
        int almacenamiento = Integer.parseInt(tfAlmacenamientoConsola.getText());
        String tipoConexion = tfTipoConexion.getText();
        
        tableConsolas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificacion", "Fabricante", "Modelo", "Años de uso", "Precio", "Tipo de consola"
            }
        ));
        DefaultTableModel model = (DefaultTableModel) tableConsolas.getModel();
            
        if ((identificacion.length() == 8) &&
            (identificacion.substring(0, 4).matches("\\d+")) &&
            (identificacion.substring(4).matches("[A-Z]+"))) {
                
            consolas.add(new Estacionaria(numeroControles, almacenamiento, tipoConexion, identificacion, fabricante, añosUso, precio, modelo));
            String tipo = "";
            for (Consola consola : consolas) {
                if (consola instanceof Portatil) {
                    tipo = "Portatil";
                } else {
                    tipo = "Estacionario";
                }
                model.addRow(new Object[] {
                    consola.getIdentificacion(),
                    consola.getFabricante(),
                    consola.getAñosUso(),
                    consola.getPrecio(),
                    consola.getModelo(),
                    tipo
                });
            }

            tableConsolas.setModel(model);
            JOptionPane.showMessageDialog(this,"Consola estacionaria agregada correctamente");                           
        } else {
            JOptionPane.showMessageDialog(null, "El numero de digitos no puede ser mayor a 4");
        }    
        
        tfIdentificacionConsola.setText("");
        tfFabricanteConsola.setText("");
        tfAñosUsoConsola.setText("");
        tfPrecioConsola.setText("");
        tfModeloConsola.setText("");
        tfNumeroControles.setText("");
        tfAlmacenamientoConsola.setText("");
        tfTipoConexion.setText("");
    }//GEN-LAST:event_btnCrearConsolaMouseClicked
    
    private void btnCrearPortatil1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearPortatil1MouseClicked
        String identificacion = tfIdentificacionPortatil.getText().toUpperCase();
        String fabricante = tfFabricantePortatil.getText();
        int añosUso = Integer.parseInt(tfAñosUsoPortatil.getText());
        int precio = Integer.parseInt(tfPrecioPortatil.getText());
        String modelo = tfModeloPortatil.getText();
        String tamañoPantalla = tfTamañoPantalla.getText();
        String bateria = tfBateriaPortatil.getText();
        boolean tieneEstuche = false;
        
        if (rbSi.isSelected()) {
            tieneEstuche = true;
        } else if (rbNo.isSelected()) {
            tieneEstuche = false;
        }
        
        tableConsolas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificacion", "Fabricante", "Modelo", "Años de uso", "Precio" , "Tipo de consola"
            }
        ));
        DefaultTableModel model = (DefaultTableModel) tableConsolas.getModel();
        
        if ((identificacion.length() == 8) &&
            (identificacion.substring(0, 4).matches("\\d+")) &&
            (identificacion.substring(4).matches("[A-Z]+"))) {
                
            consolas.add(new Portatil(tamañoPantalla, bateria, tieneEstuche, identificacion, fabricante, añosUso, precio, modelo));
            String tipo = "";
            for (Consola consola : consolas) {
                if (consola instanceof Portatil) {
                    tipo = "Portatil";
                } else {
                    tipo = "Estacionario";
                }
                model.addRow(new Object[] {
                    consola.getIdentificacion(),
                    consola.getFabricante(),
                    consola.getAñosUso(),
                    consola.getPrecio(),
                    consola.getModelo(),
                    tipo
                });
            }

            tableConsolas.setModel(model);
            JOptionPane.showMessageDialog(this,"Consola portatil agregada correctamente");                           
        } else {
            JOptionPane.showMessageDialog(null, "El numero de digitos no puede ser mayor a 4");
        }
        
        tfIdentificacionPortatil.setText("");
        tfFabricantePortatil.setText("");
        tfAñosUsoPortatil.setText("");
        tfPrecioPortatil.setText("");
        tfModeloPortatil.setText("");
        tfTamañoPantalla.setText("");
        tfBateriaPortatil.setText("");
        rbSi.setSelected(false);
        rbNo.setSelected(false);
    }//GEN-LAST:event_btnCrearPortatil1MouseClicked

    private void tableConsolasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableConsolasMouseClicked
        if (evt.isMetaDown()) {
            if (tableConsolas.getSelectedRow() >= 0) {
                popUpMenu.show(evt.getComponent(), evt.getX(), evt.getY());
            }     
        }
    }//GEN-LAST:event_tableConsolasMouseClicked
private int filaSeleccionada = -1;
    
    private void btnModificarConsolaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarConsolaMouseClicked
        if (filaSeleccionada >= 0 && filaSeleccionada < consolas.size()) {
            String identificacion = tfIdentificacionConsola1.getText().toUpperCase();
            String fabricante = tfFabricanteConsola1.getText();
            int añosUso = Integer.parseInt(tfAñosUsoConsola1.getText());
            int precio = Integer.parseInt(tfPrecioConsola1.getText());
            String modelo = tfModeloConsola1.getText();
            int numeroControles = Integer.parseInt(tfNumeroControles1.getText());
            int almacenamiento = Integer.parseInt(tfAlmacenamientoConsola1.getText());
            String tipoConexion = tfTipoConexion1.getText();

            if (filaSeleccionada >= 0 && filaSeleccionada < consolas.size()) {
                consolas.remove(filaSeleccionada);
                Consola nuevaConsola = new Estacionaria(numeroControles, almacenamiento, tipoConexion, identificacion, fabricante, añosUso, precio, modelo);

                consolas.add(filaSeleccionada, nuevaConsola);
                
                DefaultTableModel model = (DefaultTableModel) tableConsolas.getModel();
                model.removeRow(filaSeleccionada);
                model.insertRow(filaSeleccionada, new Object[] {
                    nuevaConsola.getIdentificacion(),
                    nuevaConsola.getFabricante(),
                    nuevaConsola.getModelo(),
                    nuevaConsola.getAñosUso(),
                    nuevaConsola.getPrecio(),
                    "Estacionaria"
                });
                dialogModificarConsola.setVisible(false);
                JOptionPane.showMessageDialog(this, "Consola modificada correctamente");
            }
            filaSeleccionada = -1;
        }
    }//GEN-LAST:event_btnModificarConsolaMouseClicked

    private void modificarConsolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarConsolaActionPerformed
        filaSeleccionada = tableConsolas.getSelectedRow();
        dialogModificarConsola.pack();
        dialogModificarConsola.setModal(true);
        dialogModificarConsola.setLocationRelativeTo(this);
        dialogModificarConsola.setVisible(true);
    }//GEN-LAST:event_modificarConsolaActionPerformed

    private void listarJuegosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarJuegosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listarJuegosActionPerformed

    private void eliminarConsolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarConsolaActionPerformed
        int filaSeleccionada = tableConsolas.getSelectedRow();
    
        if (filaSeleccionada >= 0) {
            int confirmacion = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que quieres eliminar esta consola?", "Confirmación", JOptionPane.YES_NO_OPTION);

            if (confirmacion == JOptionPane.YES_OPTION) {
                // Realiza la eliminación de la consola de la lista 'consolas' y de la fila en la tabla.
                consolas.remove(filaSeleccionada);
                DefaultTableModel model = (DefaultTableModel) tableConsolas.getModel();
                model.removeRow(filaSeleccionada);

                // Muestra un mensaje indicando que la consola fue eliminada.
                JOptionPane.showMessageDialog(this, "Consola eliminada correctamente");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona una consola para eliminar");
        }
    }//GEN-LAST:event_eliminarConsolaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearConsola;
    private javax.swing.JButton btnCrearPortatil1;
    private javax.swing.JButton btnModificarConsola;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JDialog dialogModificarConsola;
    private javax.swing.JDialog dialogVerJuegos;
    private javax.swing.JMenuItem eliminarConsola;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem listarJuegos;
    private javax.swing.JMenuItem modificarConsola;
    private javax.swing.JPopupMenu popUpMenu;
    private javax.swing.JRadioButton rbNo;
    private javax.swing.JRadioButton rbSi;
    private javax.swing.JTable tableConsolas;
    private javax.swing.JTextField tfAlmacenamientoConsola;
    private javax.swing.JTextField tfAlmacenamientoConsola1;
    private javax.swing.JTextField tfAñosUsoConsola;
    private javax.swing.JTextField tfAñosUsoConsola1;
    private javax.swing.JTextField tfAñosUsoPortatil;
    private javax.swing.JTextField tfBateriaPortatil;
    private javax.swing.JTextField tfFabricanteConsola;
    private javax.swing.JTextField tfFabricanteConsola1;
    private javax.swing.JTextField tfFabricantePortatil;
    private javax.swing.JTextField tfIdentificacionConsola;
    private javax.swing.JTextField tfIdentificacionConsola1;
    private javax.swing.JTextField tfIdentificacionPortatil;
    private javax.swing.JTextField tfModeloConsola;
    private javax.swing.JTextField tfModeloConsola1;
    private javax.swing.JTextField tfModeloPortatil;
    private javax.swing.JTextField tfNumeroControles;
    private javax.swing.JTextField tfNumeroControles1;
    private javax.swing.JTextField tfPrecioConsola;
    private javax.swing.JTextField tfPrecioConsola1;
    private javax.swing.JTextField tfPrecioPortatil;
    private javax.swing.JTextField tfTamañoPantalla;
    private javax.swing.JTextField tfTipoConexion;
    private javax.swing.JTextField tfTipoConexion1;
    // End of variables declaration//GEN-END:variables
}
